### ISSUE TITLE
How to Deploy on AWS

### ISSUE THREAD

**Issue by philipz** [emmanuel/coreos-skydns-cloudformation#1]
Hi Emmanuel,
I also look for the CoreOS + SkyDNS combine solution. Would you mind share the buildup step on AWS. Thanks!

**Comment by emmanuel** [comment]
Steps:
1. Clone this repo and upload the `cloudformation-template.json` file to an S3 bucket
2. Go to CloudFormation in the AWS console, and define a new stack
3. In the first step of setting up the new stack, provide the URL to the `cloudformation-template.json` file in your S3 bucket
4. Provide values for the rest of the parameters prompted for during the stack definition wizard

Good luck!

**Comment by philipz** [comment]
Thank you so much!!!

**Comment by ericson-cepeda** [comment]
Hi @emmanuel,

I have read: http://emmanuel.gomez.io/2014/07/working-with-coreos-on-aws.html. However, it is not so clear to me the parameter or tags to add for the fleet unit once launching the Docker container.

Thanks and happy new year.

**Comment by ericson-cepeda** [comment]
Hi @philipz,

Do you know how to set the flags for the containers? 

Thank you.

**Comment by philipz** [comment]
@ericson-cepeda, I changed the "cloudformation-template.json" file.
https://github.com/philipz/coreos-skydns-cloudformation

**Comment by emmanuel** [comment]
I was not expecting to have anyone report issues here on Github, so I was completely oblivious about this issue until a week or two ago (I suppose I could have turned off issues on this repo, but oh well). Given the age of the issue and how fast everything in this space is moving, I'm going to assume that this is no longer relevant. 

If anyone still has questions, please open new issues and I'll try to be responsive (as time permits).
