### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jmreicha** [emmanuel/coreos-skydns-cloudformation#2]
Are you running all these services on all your hosts?  I'm just starting my CoreOS journey and am not sure what services would be good to have running on each host.  Any insight?

I don't see anything here about kubernetes, are you doing anything for orchestration and management?

**Comment by emmanuel** [comment]
I was not expecting to have anyone report issues here on Github, so I was completely oblivious about this issue until a week or two ago (I suppose I could have turned off issues on this repo, but oh well). Given the age of the issue and how fast everything in this space is moving, I'm going to assume that this is no longer relevant.

If anyone still has questions, please open new issues and I'll try to be responsive (as time permits).
