### ISSUE TITLE
Use ENI & EIP to get closer to HA for NAT egress instances

### ISSUE THREAD

**Issue by emmanuel** [emmanuel/coreos-skydns-cloudformation#4]
As described [here](http://www.cakesolutions.net/teamblogs/making-aws-nat-instances-highly-available-without-the-compromises), attaching an Elastic IP (EIP) to an Elastic Network Interfaces (ENI) provides a foundation for building HA NAT.

**Comment by emmanuel** [comment]
Currently we run a script on boot on each NAT instance, which assigns the default route for the paired private subnet's route table to the booting NAT instance. The instance is assigned an IAM role that allows modifying the route table of the private subnet. 

In the ENI+EIP model, instead of updating the private subnet's route table, the route table's default route is statically configured to direct traffic to the ENI. The NAT instance assigns the appropriate ENI to itself on boot. 

The EIP is a cherry on top that presents a stable return address to the outside world. That facilitates the eventual goal of 2 NAT nodes per private subnet in a hot-standby scenario. Hot-standby remains for future work.

**Comment by emmanuel** [comment]
One stumbling point is that terraform doesn't currently support [disabling source/destination checks on the ENI](https://github.com/hashicorp/terraform/issues/2407). It looks like this [just landed in terraform](https://github.com/hashicorp/terraform/pull/2741#event-363583320), but hasn't seen a release yet.

**Comment by pidah** [comment]
disabling source/destination checks on the ENI has been added in the 0.6.2 release

**Comment by emmanuel** [comment]
True that. Time to close this!
